#!/bin/bash
#SBATCH --job-name=build_bt2_index_hg38
#SBATCH --output=build_bt2_index_hg38_%j.out
#SBATCH --error=build_bt2_index_hg38_%j.err
#SBATCH --time=04:00:00
#SBATCH --cpus-per-task=4
#SBATCH --mem=16G

module load CBI samtools/1.20 bowtie2/2.5.3

# download hg38/GRCh38 primary assembly from ensembl for seq align
wget https://ftp.ensembl.org/pub/release-111/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz

# gunzip the FASTA
gunzip Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz

# bowtie2 index (6 files with prefix hg38_index)
bowtie2-build --threads 4 Homo_sapiens.GRCh38.dna.primary_assembly.fa hg38_index
