#!/bin/bash
#SBATCH --job-name=convert_broad_to_bed
#SBATCH --output=convert_broad_to_bed.out
#SBATCH --error=convert_broad_to_bed.err
#SBATCH --time=01:00:00
#SBATCH --partition=short
#SBATCH --ntasks=1
#SBATCH --mem=4G

# Define working directory
INPUT_DIR="PATHTO/macs"      #Path where the original broadPeak files were generated
cd "$INPUT_DIR" || exit 1

# Create output directory if needed
OUTDIR="${INPUT_DIR}/macs_beds"
mkdir -p "$OUTDIR"

# Loop over all .broadPeak files
for file in *.broadPeak; do
  base=$(basename "$file" .broadPeak)
  out="${OUTDIR}/${base}.bed"
  
  # Convert to BED6: keep only the first 6 columns
  cut -f1-6 "$file" > "$out"

  echo "Converted $file → $out"
done

